USE QUANLYSV
GO

SELECT * FROM SINH_VIEN
WHERE ma_sv = '18810310208'
GO


SELECT ten_bdt FROM BAC_DAO_TAO
WHERE ma_bdt = 'BDT01'
GO

SELECT loai_hinh_dao_tao FROM BAC_DAO_TAO
WHERE ma_bdt = 'BDT01'
GO


SELECT KHOA.ten_k FROM LOP, CHUYEN_NGANH, KHOA
WHERE LOP.ma_cn = CHUYEN_NGANH.ma_cn
AND KHOA.ma_k = CHUYEN_NGANH.ma_k
AND LOP.ma_lop = 'CNPM1'
GO


-----
SELECT CHUYEN_NGANH.ten_cn FROM LOP, CHUYEN_NGANH
WHERE LOP.ma_cn = CHUYEN_NGANH.ma_cn
AND LOP.ma_lop = 'CNPM1'
GO


SELECT